name: Auto Merge Pull Requests

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Auto-merge PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list --state open --json number,isDraft,mergeable --jq '.[] | select(.isDraft == false and .mergeable == "MERGEABLE") | .number')
          for pr in $prs; do
            echo "Merging PR #$pr"
            gh pr merge $pr --merge --admin
          done
